name: PyMI CD

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      max-parallel: 100
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Test and build PyMI
      shell: cmd
      run: |
        SETLOCAL EnableDelayedExpansion
        pip install -r requirements.txt || exit /b
        pip install nose testtools wheel || exit /b
        pip install . || exit /b
        python -m unittest discover || exit /b
        python setup.py bdist_wheel || exit /b
    - uses: actions/upload-artifact@v3
      with:
        name: pymi_wheel_py${{ matrix.python-version }}
        path: 'dist'
